In [47]:
import numpy as np

lista = [[] for _ in range(3)]
i = 0
for x in np.arange(1, 10):
    lista[i].append(x-1)
    if x % 3 == 0: 
        i += 1
        
q3 = np.array(lista)
print(q3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [42]:
print(q3.transpose())

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [41]:
print(np.random.rand(3,3,3))

[[[0.78446499 0.23659595 0.73636781]
  [0.68362519 0.0780498  0.9790371 ]
  [0.18883346 0.40935862 0.46402194]]

 [[0.56072667 0.13079824 0.57929419]
  [0.62587515 0.73267195 0.68253793]
  [0.26317469 0.66435141 0.38967316]]

 [[0.79086592 0.03555249 0.00572439]
  [0.60148683 0.51065508 0.04120349]
  [0.53975881 0.08935896 0.85157195]]]
